import http from "node:http"; import {readFile} from "node:fs/promises"; import path from "node:path"; import {fileURLToPath} from "node:url";
import {loadModel,completion,unloadModel,LLAMA_3_2_1B_INST_Q4_0} from "@qvac/sdk";
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),PORT=Number(process.env.PORT||3000); let modelId=null,modelLoading=null;
async function getModel(){if(modelId)return modelId;if(!modelLoading){console.log("Loading Decision Mirror locally with QVAC...");modelLoading=loadModel({modelSrc:LLAMA_3_2_1B_INST_Q4_0,modelType:"llm",modelConfig:{ctx_size:4096},onProgress:p=>{if(Number.isFinite(p?.percentage))console.log(`Model download: ${p.percentage.toFixed(0)}%`)}})}modelId=await modelLoading;modelLoading=null;console.log("QVAC model loaded:",modelId);return modelId}
function prompt(x){const opts=x.options.map((o,i)=>`${i+1}. ${o.name}\n   Pros: ${o.pros||"None listed"}\n   Cons: ${o.cons||"None listed"}`).join("\n");return `You are Decision Mirror, a neutral decision-mapping assistant.\n\nThe user is considering:\n${x.question}\n\nTheir priorities:\n${x.priorities||"Not specified"}\n\nOptions:\n${opts}\n\nCreate a balanced decision map. Do NOT choose a winner and do not tell the user what they should do. Return concise Markdown with exactly these sections:\n\n## Decision Frame\nRestate the decision neutrally.\n\n## Option Comparison\nFor each option, summarize likely benefits, drawbacks, uncertainties, and which stated priorities it serves.\n\n## Trade-offs\nIdentify the key trade-offs between the options.\n\n## Questions Worth Asking\nGive 3-5 questions that could change the decision.\n\n## Information Gaps\nList facts the user may want to verify before deciding.\n\n## Reflection\nGive a short neutral reflection about the user's priorities.\n\nNever invent prices, statistics, laws, guarantees, or current facts. Clearly mark uncertainty.`}
async function decision(req,res){try{let body="";for await(const c of req)body+=c;const x=JSON.parse(body);if(!x.question?.trim()||!Array.isArray(x.options)||x.options.length<2)throw Error("Enter a decision and at least two options.");const id=await getModel();const run=completion({modelId:id,history:[{role:"user",content:prompt(x)}],stream:true});const r=await run.final;const analysis=r?.contentText||r?.raw?.fullText||r?.text||"";if(!analysis.trim())throw Error("QVAC returned an empty analysis.");res.writeHead(200,{"Content-Type":"application/json"});res.end(JSON.stringify({analysis,local:true,sdk:"QVAC 0.19.1"}))}catch(e){console.error(e);res.writeHead(500,{"Content-Type":"application/json"});res.end(JSON.stringify({error:e?.message||String(e)}))}}
const routes={"/": ["public/index.html","text/html; charset=utf-8"],"/index.html":["public/index.html","text/html; charset=utf-8"],"/app.js":["public/app.js","text/javascript; charset=utf-8"],"/styles.css":["public/styles.css","text/css; charset=utf-8"]};
const server=http.createServer(async(req,res)=>{if(req.method==="POST"&&req.url==="/api/decision")return decision(req,res);if(req.method!=="GET"){res.writeHead(405);return res.end("Method not allowed")}const route=routes[req.url];if(!route){res.writeHead(404);return res.end("Not found")}try{const c=await readFile(path.join(__dirname,route[0]));res.writeHead(200,{"Content-Type":route[1]});res.end(c)}catch{res.writeHead(404);res.end("File not found")}});
server.listen(PORT,()=>{console.log(`Decision Mirror running at http://localhost:${PORT}`);console.log("AI inference: QVAC on-device/local")});
async function shutdown(){try{if(modelId)await unloadModel({modelId})}catch(e){console.error(e)}finally{process.exit(0)}}process.on("SIGINT",shutdown);process.on("SIGTERM",shutdown);
